In [81]:
import pandas as pd
import random
import pickle

In [82]:
# Define some example categories
trial_types = ['Phase 1', 'Phase 2', 'Phase 3', 'Phase 4']
therapeutic_areas = ['Oncology', 'Cardiology', 'Neurology', 'Gastroenterology']
trial_phases = [1, 2, 3, 4]
inclusion_criteria = ['Yes', 'No']

In [83]:
# Generate synthetic data
data = []
for _ in range(1000):  # Generate 100 data points, you can adjust this number
    trial_type = random.choice(trial_types)
    therapeutic_area = random.choice(therapeutic_areas)
    trial_phase = random.choice(trial_phases)
    num_patients = random.randint(50, 300)
    inclusion = random.choice(inclusion_criteria)
    site_capacity = random.randint(50, 300)
    activation_time = random.randint(60, 300)  # Adjust range based on your use case
    
    data.append([trial_type, therapeutic_area, trial_phase, num_patients, inclusion, site_capacity, activation_time])

In [106]:
# Create a DataFrame
columns = ['Trial_Type', 'Therapeutic_Area', 'Trial_Phase', 'Number_of_Patients', 'Inclusion_Criteria', 'Site_Capacity', 'Activation_Time']
df = pd.DataFrame(data, columns=columns)

# Save it as a CSV file
df.to_csv('clinical_trial_data.csv', index=False)

In [107]:
df

,Trial_Type,Therapeutic_Area,Trial_Phase,Number_of_Patients,Inclusion_Criteria,Site_Capacity,Activation_Time
0,Phase 1,Cardiology,4,74,Yes,144,261
1,Phase 1,Neurology,2,202,Yes,272,68
2,Phase 1,Oncology,4,60,Yes,227,168
3,Phase 2,Gastroenterology,3,155,No,251,255
4,Phase 2,Gastroenterology,3,141,No,149,128
...,...,...,...,...,...,...,...
995,Phase 1,Gastroenterology,3,226,No,214,228
996,Phase 4,Gastroenterology,2,129,No,51,207
997,Phase 2,Neurology,2,222,Yes,114,299
998,Phase 4,Oncology,3,276,No,126,129
999,Phase 2,Oncology,1,77,Yes,135,213

In [86]:
# Save it as a CSV file
df.to_csv('clinical_trial_data.csv', index=False)

In [108]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
df['Trial_Type']= label_encoder.fit_transform(df['Trial_Type']) 
  
df['Trial_Type'].unique() 
df['Therapeutic_Area']= label_encoder.fit_transform(df['Therapeutic_Area']) 
  
df['Therapeutic_Area'].unique() 
df['Inclusion_Criteria']= label_encoder.fit_transform(df['Inclusion_Criteria']) 
  
df['Inclusion_Criteria'].unique()

array([1, 0])

In [109]:
df

,Trial_Type,Therapeutic_Area,Trial_Phase,Number_of_Patients,Inclusion_Criteria,Site_Capacity,Activation_Time
0,0,0,4,74,1,144,261
1,0,2,2,202,1,272,68
2,0,3,4,60,1,227,168
3,1,1,3,155,0,251,255
4,1,1,3,141,0,149,128
...,...,...,...,...,...,...,...
995,0,1,3,226,0,214,228
996,3,1,2,129,0,51,207
997,1,2,2,222,1,114,299
998,3,3,3,276,0,126,129
999,1,3,1,77,1,135,213

In [51]:
#from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler() 
#data_scaled = scaler.fit_transform(df)
#df = pd.DataFrame.from_records(data_scaled)

In [136]:
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

# In[7]:


from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)


# In[8]:


from sklearn.metrics import r2_score
Y_predict = lr_model.predict(X_test)
r2 = r2_score(y_test, Y_predict)
print('R2 score is {}'.format(r2))


# In[10]:


# Saving model to disk
pickle.dump(lr_model, open('lr_model.pkl','wb'))

R2 score is 0.0018335866833841807

In [135]:
len(Y_predict)

300

In [124]:
X

array([[  0,   0,   4,  74,   1, 144],
       [  0,   2,   2, 202,   1, 272],
       [  0,   3,   4,  60,   1, 227],
       ...,
       [  1,   2,   2, 222,   1, 114],
       [  3,   3,   3, 276,   0, 126],
       [  1,   3,   1,  77,   1, 135]], dtype=int64)

In [125]:
X

array([[  0,   0,   4,  74,   1, 144],
       [  0,   2,   2, 202,   1, 272],
       [  0,   3,   4,  60,   1, 227],
       ...,
       [  1,   2,   2, 222,   1, 114],
       [  3,   3,   3, 276,   0, 126],
       [  1,   3,   1,  77,   1, 135]], dtype=int64)